# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-lambda', '~> 1'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-secretsmanager', '~> 1'
gem 'aws-sdk-ssm', '~> 1'

# net-ssh requires the following gems for ed25519 support:
gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
gem 'ed25519', '>= 1.2', '< 2.0'

gem 'inspec', '=4.38.9'
gem 'inspec-bin', '=4.38.9'
gem 'train-awsssm', '=0.3.0'
gem 'train-kubernetes', '>=0.1.6'
